### ISSUE TITLE
Additional Features

### ISSUE THREAD

**Issue by UniAdrian** [UniAdrian/CC2CoronoTracker#10]
Please think about possible features and comment them below. 
I suggest small votes in regular intervals to decide which features are nice to have and possible in the remaining time frame.

I recommend a feature lock from the 10th of july forwards at the latest to concentrate on bug fixing.

Polishing will be part of the coding week.

One idea would be e.g. day/night themes, the google maps integration of localization. (The latter is already part of my current implementations since it is good practice to utilize the strings resources anyway...)

**Edit**:
We can do votes by using the reaction system, as well. See blow, where i upvoted my own ideas.

**Comment by UniAdrian** [comment]
It would be cool if we could export the personal QR code. E.g. print it, store it for a reinstall etc.

**Comment by UniAdrian** [comment]
I would vote for an onboarding screen.
More details at [the documentation](https://developer.android.com/training/tv/playback/onboarding)

**Comment by JRose108** [comment]
> I would vote for an onboarding screen.
> More details at [the documentation](https://developer.android.com/training/tv/playback/onboarding)

**Comment by JRose108** [comment]
Onboarding screen is an additional feature right.It will be cool if we add this
