### ISSUE TITLE
Add Calendar view

### ISSUE THREAD

**Issue by UniAdrian** [UniAdrian/CC2CoronoTracker#20]
Add a calendar view.
Allow the user to navigate to other app features (e.g. exposures, statistics, map,...) directly from the calendar.

**Comment by JRose108** [comment]
Added a calendar view that fetches exposure on a given day

**Comment by JRose108** [comment]
CalenderView shows Contact that has exposure on the given day

**Comment by JRose108** [comment]
CalendeView leads to Map to display the given exposure

**Comment by UniAdrian** [comment]
:thumbsup:

**Comment by UniAdrian** [comment]
Is there a specific reason you didnt simply integrate the functionality into the xisting map fragment and instead rolled your own?
No pressure changing it now, we are running out of time. Just curious. ;)

**Comment by JRose108** [comment]
Although it was easy to integrate the functionality into the existing map fragment, I started with a new fragment not disturbing the existing code. Due to time, I couldn't change that

**Comment by UniAdrian** [comment]
Allright, no problem. As i said: Just curious. ;)

**Comment by JRose108** [comment]
Added all the features but code and UI can be still improved.
